[tool.black]
line-length = 200
target-version = ['py38','py39','py310','py311','py312','py313']
include = '\.pyi?$'
exclude = '''
/(
    \.eggs
  | \.git
  | \.mypy_cache
  | \.tox
  | \.venv
  | _build
  | build
  | dist
)/
'''
